spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${kafka.binder.brokers}
          defaultBrokerPort: ${kafka.binder.defaultBrokerPort}
          zk-nodes: ${kafka.binder.zkNodes}
          defaultZkPort: ${kafka.binder.defaultZkPort}
      bindings:
        output:
          destination: ${kafka.destination}

  rabbitmq:
    addresses: ${rabbitmq.address}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

logging:
  level.root: info
  level.org.springframework.cloud: DEBUG
  level.org.springframework.cloud.sleuth: TRACE
  level.org.springframework.cloud.sleuth.log: DEBUG
  level.org.springframework.cloud.sleuth.trace: DEBUG
  level.org.springframework.cloud.sleuth.instrument.rxjava: DEBUG
  level.com.jinjiang: trace



