spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.2.193
          defaultBrokerPort: 9092
          zk-nodes: 192.168.2.193
          defaultZkPort: 2181
      bindings:
        output:
          destination: mydest