spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${kafka.binder.brokers}
          #defaultBrokerPort: 9092
          zk-nodes: ${kafka.binder.zkNodes}
          #defaultZkPort: 2181
      bindings:
        output:
          destination: ${kafka.destination}
          #content-type: application/json
