spring:
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: ${kafka.binder.brokers}
          defaultBrokerPort: ${kafka.binder.defaultBrokerPort}
          brokers: ${kafka.binder.zkNodes}
          defaultZkPort: ${kafka.binder.defaultZkPort}
          headers:
            - X-B3-TraceId
            - X-B3-SpanId
            - X-B3-Sampled
            - X-B3-ParentSpanId
            - X-Span-Name
            - X-Process-Id

sleuth:
   # not use sleuth stream to trace zipkin server itself
    enabled: false
    #refer to org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration.java
    hystrix:
      strategy:
        enabled: false

zipkin:
  storage:
    type: mem #mysql #mem
