spring:
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: 192.168.2.193
          brokers: 192.168.2.193
          headers:
            - X-B3-TraceId
            - X-B3-SpanId
            - X-B3-Sampled
            - X-B3-ParentSpanId
            - X-Span-Name
            - X-Process-Id